[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.slack]
animation = "fromRight"
command = "slack"
class = "slack"
size = "75% 75%"
lazy = true

[scratchpads.vesktop]
animation = "fromRight"
command = "vesktop"
class = "vesktop"
size = "75% 75%"
lazy = true

